src/apps/Automation.Web/PersonalAutomations.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace PersonalAutomations.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

src/apps/Automation.Web/PersonalAutomations.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PersonalAutomations.Web.Data.Classes;
using PersonalAutomations.Web.Interfaces;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;

namespace PersonalAutomations.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly PersonalAutomations.Web.Data.ApplicationDbContext _context;

        private readonly ILogger<IndexModel> _logger;

        private readonly IMessageProcessor _messageProcessor;

        private readonly UserManager<IdentityUser> _userManager;

        public IndexModel(
            ILogger<IndexModel> logger, 
            PersonalAutomations.Web.Data.ApplicationDbContext contex, 
            IMessageProcessor MessageProcessor,
            UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _context = contex;
            _messageProcessor = MessageProcessor;
            _userManager = userManager;
        }

        [BindProperty]
        public List<AutomationAction> ActiveAutomations { get; set; } = default!;

        public void OnGet()
        {
            ActiveAutomations = _context.AutomationActions.Include(p => p.Parameters).Where(a => a.IsActive).ToList();
        }

        public async Task<IActionResult> OnPostRunAutomation(string ActionKeyword, List<ActionParameter> parameters)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                var action = _context.AutomationActions.Include(p => p.Parameters).Where(a => a.ActionKeyword == ActionKeyword).FirstOrDefault();
                if (action != null)
                {
                    // Add the values to the parameters before we send it to the message queue
                    foreach (var item in parameters)
                    {
                        action.Parameters.Where(p => p.Name == item.Name).First().Value = item.Value;
                    }

                    // Serialize the object into Json to send to the message queue
                    var messageBody = JsonConvert.SerializeObject(action);

                    // pusht the message to the queue
                    _messageProcessor.PublishMessage(messageBody, User.Identity.Name);

                    var AlertMessage = "Message Sent!";

                    // set the message to the session so the web page can display it to the user
                    HttpContext.Session.SetString("AlertMessage", AlertMessage);

                    // redirect back to the default page so it loads all the automations back up correctly
                    return RedirectToPage("./Index");
                }
            }

            return Page();
        }
    }
}

src/apps/Automation.Web/PersonalAutomations.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PersonalAutomations.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

src/apps/Automation.Web/PersonalAutomations.Web/Pages/Index.cshtml
@page

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Personal Automations</h1>
</div>

@if (SignInManager.IsSignedIn(User))
{
    @if (HttpContext.Session.TryGetValue("AlertMessage", out byte[] res))
    {
        <div class="alert alert-success alert-dismissible fade show">
            @HttpContext.Session.GetString("AlertMessage")
            <button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        HttpContext.Session.Remove("AlertMessage");
    }

    <div class="row row-cols-1 row-cols-lg-3">
        @foreach(var automation in Model.ActiveAutomations)
        {
            <form method="post">
                <div class="col">
                    <div class="card h-100 text-white bg-dark rounded-5">
                        @Html.DisplayFor(modelItem => automation.Name)                                        
                    </div>
                    <table class="table table-striped">
                        <thead>
                            <th>Parameter Name</th>
                            <th>Parameter Value</th>
                        </thead>
                        <tbody>                                    
                            @for(var i = 0; i < automation.Parameters.Count; i++)// foreach (var param in automation.Parameters)
                            {
                                <tr>
                                    <td>@automation.Parameters.ElementAt(i).Name<input type="hidden" name="[@i].Name" value="@automation.Parameters.ElementAt(i).Name" /></td>
                                    <td><input type="text" name="[@i].Value" /></td>
                                </tr>
                                    @* @Html.DisplayFor(item => param.Name)
                                    @Html.EditorFor(item => param.Value, "", param.Name) *@
                            }
                        </tbody>
                    </table>

                    <input type="submit" class="btn btn-primary" asp-page-handler="RunAutomation" asp-route-ActionKeyword="@automation.ActionKeyword" name="action" value="Run Automation" />
                </div>
            </form>
        }
    </div>
}